# Generated by Django 3.2.13 on 2022-05-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=1024, null=True)),
                ('token', models.CharField(max_length=4, null=True)),
                ('activated', models.BooleanField(default=False)),
                ('token_sent_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
